In [7]:
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
import numpy as np
import pandas as pd

## Loading data

In [8]:
train_data=pd.read_csv('0000000000002429_training_titanic_x_y_train.csv',delimiter=",")
train_data

Pclass                                            Name     Sex   Age  \
0         2   Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female  29.0   
1         3               Williams, Mr. Howard Hugh "Harry"    male   NaN   
2         2  Morley, Mr. Henry Samuel ("Mr Henry Marshall")    male  39.0   
3         3     Palsson, Mrs. Nils (Alma Cornelia Berglund)  female  29.0   
4         3                          Sutehall, Mr. Henry Jr    male  25.0   
..      ...                                             ...     ...   ...   
663       2                             Ilett, Miss. Bertha  female  17.0   
664       3                        Morrow, Mr. Thomas Rowan    male   NaN   
665       3                                   Bing, Mr. Lee    male  32.0   
666       3                     Strandberg, Miss. Ida Sofia  female  22.0   
667       3                  Murphy, Miss. Katherine "Kate"  female   NaN   

     SibSp  Parch           Ticket     Fare Cabin Embarked  Survived  
0        1      0           228414  26.0000   NaN        S         1  
1        0      0         A/5 2466   8.0500   NaN        S         0  
2        0      0           250655  26.0000   NaN        S         0  
3        0      4           349909  21.0750   NaN        S         0  
4        0      0  SOTON/OQ 392076   7.0500   NaN        S         0  
..     ...    ...              ...      ...   ...      ...       ...  
663      0      0       SO/C 14885  10.5000   NaN        S         1  
664      0      0           372622   7.7500   NaN        Q         0  
665      0      0             1601  56.4958   NaN        S         1  
666      0      0             7553   9.8375   NaN        S         0  
667      1      0           367230  15.5000   NaN        Q         1  

[668 rows x 11 columns]

In [9]:
test_data=pd.read_csv("0000000000002429_test_titanic_x_test.csv",delimiter=",")
test_data

Pclass                                               Name     Sex   Age  \
0         2                     Davies, Master. John Morgan Jr    male   8.0   
1         1                        Leader, Dr. Alice (Farnham)  female  49.0   
2         3                            Kilgannon, Mr. Thomas J    male   NaN   
3         2  Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...  female  24.0   
4         1                          McGough, Mr. James Robert    male  36.0   
..      ...                                                ...     ...   ...   
218       3                        Lindqvist, Mr. Eino William    male  20.0   
219       1                  Butt, Major. Archibald Willingham    male  45.0   
220       1  Penasco y Castellana, Mrs. Victor de Satode (M...  female  17.0   
221       3                   Holm, Mr. John Fredrik Alexander    male  43.0   
222       2           Navratil, Mr. Michel ("Louis M Hoffman")    male  36.5   

     SibSp  Parch             Ticket      Fare Cabin Embarked  
0        1      1         C.A. 33112   36.7500   NaN        S  
1        0      0              17465   25.9292   D17        S  
2        0      0              36865    7.7375   NaN        Q  
3        2      1             243847   27.0000   NaN        S  
4        0      0           PC 17473   26.2875   E25        S  
..     ...    ...                ...       ...   ...      ...  
218      1      0  STON/O 2. 3101285    7.9250   NaN        S  
219      0      0             113050   26.5500   B38        S  
220      1      0           PC 17758  108.9000   C65        C  
221      0      0             C 7075    6.4500   NaN        S  
222      0      2             230080   26.0000    F2        S  

[223 rows x 10 columns]

## Data Preprocessing and Cleaning

In [10]:
title_in_train=[]
for i in train_data['Name']:
    title_in_train.append(i.split()[1][0:-1])
    
title_in_train = np.array(title_in_train)

title_in_train[title_in_train == "Mr"]=0
title_in_train[title_in_train == "Mrs"]=1
title_in_train[title_in_train == "Miss"]=2
title_in_train[title_in_train == "Master"]=3
title_in_train[(title_in_train != '0')&(title_in_train != '1')&(title_in_train != '2')&(title_in_train != '3')]=4
title_in_train = np.array(title_in_train,dtype =int)
title_in_train

array([1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 2, 4, 1,
       1, 0, 1, 2, 0, 0, 0, 0, 1, 0, 4, 2, 4, 0, 3, 3, 0, 0, 0, 0, 1, 2,
       0, 0, 0, 0, 4, 4, 2, 3, 0, 1, 0, 2, 0, 0, 0, 1, 0, 0, 0, 1, 2, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 2, 4, 1, 4, 1, 0, 1, 0, 2, 0, 0, 0,
       0, 0, 4, 1, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 4,
       2, 1, 0, 2, 0, 0, 0, 0, 2, 2, 1, 4, 2, 2, 2, 0, 0, 0, 0, 1, 0, 2,
       0, 0, 4, 1, 0, 0, 0, 4, 0, 1, 0, 0, 0, 0, 1, 0, 2, 2, 1, 0, 1, 2,
       1, 0, 1, 0, 2, 1, 1, 2, 0, 0, 0, 4, 0, 0, 0, 3, 0, 4, 1, 0, 4, 2,
       1, 0, 0, 0, 0, 2, 1, 0, 1, 3, 0, 2, 1, 0, 0, 2, 2, 0, 0, 0, 0, 0,
       0, 0, 2, 4, 2, 0, 2, 0, 1, 0, 0, 3, 1, 1, 2, 0, 2, 0, 0, 3, 2, 2,
       2, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 3, 1, 0, 0, 0, 0, 1, 0, 2, 0, 0,
       0, 1, 0, 0, 2, 1, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 4,
       0, 0, 1, 0, 0, 0, 3, 3, 0, 1, 2, 0, 0, 3, 0, 0, 0, 1, 2, 0, 0, 2,
       2, 0, 0, 0, 2, 0, 0, 2, 1, 2, 3, 0, 0, 2, 0,

In [11]:
title_in_test = []

for i in test_data['Name']:
    title_in_test.append(i.split()[1][0:-1])
    
title_in_test = np.array(title_in_test)

title_in_test[title_in_test == "Mr"]=0
title_in_test[title_in_test == "Mrs"]=1
title_in_test[title_in_test == "Miss"]=2
title_in_test[title_in_test == "Master"]=3
title_in_test[(title_in_test != '0')&(title_in_test != '1')&(title_in_test != '2')&(title_in_test != '3')]=4
title_in_test = np.array(title_in_test,dtype =int)
title_in_test

array([3, 4, 0, 1, 0, 0, 4, 0, 2, 0, 2, 0, 2, 2, 0, 0, 0, 3, 0, 2, 2, 0,
       2, 2, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 2, 0, 4, 0,
       2, 3, 0, 2, 0, 0, 0, 2, 1, 2, 0, 0, 3, 0, 0, 0, 0, 4, 1, 2, 1, 4,
       0, 4, 2, 4, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2,
       0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 3, 2, 2, 4, 2, 3, 2, 2, 4, 4, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 3, 3, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0,
       2, 0, 0, 2, 0, 3, 0, 2, 1, 2, 2, 0, 0, 0, 1, 2, 1, 4, 2, 0, 2, 0,
       0, 0, 0, 2, 0, 0, 3, 2, 1, 0, 1, 0, 2, 0, 0, 0, 1, 0, 0, 2, 2, 2,
       1, 4, 0, 4, 0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 0, 0, 2, 2, 0, 0, 0, 4,
       4, 0, 0])

In [12]:
train_data.drop('Name',axis=1,inplace=True)
train_data.drop('Ticket',axis=1,inplace=True)

In [13]:
train_data

Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked  Survived
0         2  female  29.0      1      0  26.0000   NaN        S         1
1         3    male   NaN      0      0   8.0500   NaN        S         0
2         2    male  39.0      0      0  26.0000   NaN        S         0
3         3  female  29.0      0      4  21.0750   NaN        S         0
4         3    male  25.0      0      0   7.0500   NaN        S         0
..      ...     ...   ...    ...    ...      ...   ...      ...       ...
663       2  female  17.0      0      0  10.5000   NaN        S         1
664       3    male   NaN      0      0   7.7500   NaN        Q         0
665       3    male  32.0      0      0  56.4958   NaN        S         1
666       3  female  22.0      0      0   9.8375   NaN        S         0
667       3  female   NaN      1      0  15.5000   NaN        Q         1

[668 rows x 9 columns]

In [14]:
test_data.drop('Name',axis=1,inplace=True)
test_data.drop('Ticket',axis=1,inplace=True)

In [15]:
test_data

Pclass     Sex   Age  SibSp  Parch      Fare Cabin Embarked
0         2    male   8.0      1      1   36.7500   NaN        S
1         1  female  49.0      0      0   25.9292   D17        S
2         3    male   NaN      0      0    7.7375   NaN        Q
3         2  female  24.0      2      1   27.0000   NaN        S
4         1    male  36.0      0      0   26.2875   E25        S
..      ...     ...   ...    ...    ...       ...   ...      ...
218       3    male  20.0      1      0    7.9250   NaN        S
219       1    male  45.0      0      0   26.5500   B38        S
220       1  female  17.0      1      0  108.9000   C65        C
221       3    male  43.0      0      0    6.4500   NaN        S
222       2    male  36.5      0      2   26.0000    F2        S

[223 rows x 8 columns]

In [16]:
def gen(s):
    if s == "male":
        return 0
    elif s == "female":
        return 1

In [17]:
train_data["Sex"] = train_data["Sex"].apply(gen)
train_data.head(3)

Pclass  Sex   Age  SibSp  Parch   Fare Cabin Embarked  Survived
0       2    1  29.0      1      0  26.00   NaN        S         1
1       3    0   NaN      0      0   8.05   NaN        S         0
2       2    0  39.0      0      0  26.00   NaN        S         0

In [18]:
train_data.isnull().sum()

Pclass        0
Sex           0
Age         132
SibSp         0
Parch         0
Fare          0
Cabin       514
Embarked      1
Survived      0
dtype: int64

In [19]:
train_data["Age"].fillna(train_data["Age"].mean(),inplace = True)
train_data.isnull().sum()

Pclass        0
Sex           0
Age           0
SibSp         0
Parch         0
Fare          0
Cabin       514
Embarked      1
Survived      0
dtype: int64

In [20]:
train_data.loc[train_data['Cabin'].isnull(),'Cabin']=0
train_data.loc[train_data['Cabin']!=0,'Cabin']=1

In [21]:
train_data.isnull().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Cabin       0
Embarked    1
Survived    0
dtype: int64

In [22]:
# let s=1,Q=2,C=3
def emba(x):
    if x=='S':
        return 1
    elif x=='Q':
        return 2
    else:
        return 3

In [23]:
train_data["Embarked"]=train_data['Embarked'].apply(emba)

In [24]:
train_data

Pclass  Sex       Age  SibSp  Parch     Fare Cabin  Embarked  Survived
0         2    1  29.00000      1      0  26.0000     0         1         1
1         3    0  29.70056      0      0   8.0500     0         1         0
2         2    0  39.00000      0      0  26.0000     0         1         0
3         3    1  29.00000      0      4  21.0750     0         1         0
4         3    0  25.00000      0      0   7.0500     0         1         0
..      ...  ...       ...    ...    ...      ...   ...       ...       ...
663       2    1  17.00000      0      0  10.5000     0         1         1
664       3    0  29.70056      0      0   7.7500     0         2         0
665       3    0  32.00000      0      0  56.4958     0         1         1
666       3    1  22.00000      0      0   9.8375     0         1         0
667       3    1  29.70056      1      0  15.5000     0         2         1

[668 rows x 9 columns]

In [25]:
train_data.describe()

Pclass         Sex         Age       SibSp       Parch        Fare  \
count  668.000000  668.000000  668.000000  668.000000  668.000000  668.000000   
mean     2.296407    0.360778   29.700560    0.528443    0.407186   32.064552   
std      0.831638    0.480586   12.753571    1.080327    0.854695   45.320835   
min      1.000000    0.000000    0.670000    0.000000    0.000000    0.000000   
25%      2.000000    0.000000   23.000000    0.000000    0.000000    7.925000   
50%      3.000000    0.000000   29.700560    0.000000    0.000000   14.750000   
75%      3.000000    1.000000   35.000000    1.000000    0.000000   31.275000   
max      3.000000    1.000000   80.000000    8.000000    6.000000  512.329200   

         Embarked    Survived  
count  668.000000  668.000000  
mean     1.476048    0.402695  
std      0.807217    0.490808  
min      1.000000    0.000000  
25%      1.000000    0.000000  
50%      1.000000    0.000000  
75%      2.000000    1.000000  
max      3.000000    1.000000

In [26]:
training_data=train_data.values
x_train=training_data[:,:-1]
y_train=training_data[:,-1]
x_train=np.append(x_train,title_in_train.reshape(-1,1),axis=1)

In [27]:
x_train.shape

(668, 9)

In [28]:
y_train=y_train.astype('int')

In [29]:
x_train=x_train.astype('int')

In [30]:
x_train

array([[ 2,  1, 29, ...,  0,  1,  1],
       [ 3,  0, 29, ...,  0,  1,  0],
       [ 2,  0, 39, ...,  0,  1,  0],
       ...,
       [ 3,  0, 32, ...,  0,  1,  0],
       [ 3,  1, 22, ...,  0,  1,  2],
       [ 3,  1, 29, ...,  0,  2,  2]])

In [31]:
# working on testing data
# for sex
test_data["Sex"] = test_data["Sex"].apply(gen)
# for embarked
test_data["Embarked"]=test_data['Embarked'].apply(emba)
# for age
test_data["Age"].fillna(test_data["Age"].mean(),inplace = True)
# for cabin
test_data.loc[test_data['Cabin'].isnull(),'Cabin']=0
test_data.loc[test_data['Cabin']!=0,'Cabin']=1
test_data

Pclass  Sex        Age  SibSp  Parch      Fare Cabin  Embarked
0         2    0   8.000000      1      1   36.7500     0         1
1         1    1  49.000000      0      0   25.9292     1         1
2         3    0  29.694775      0      0    7.7375     0         2
3         2    1  24.000000      2      1   27.0000     0         1
4         1    0  36.000000      0      0   26.2875     1         1
..      ...  ...        ...    ...    ...       ...   ...       ...
218       3    0  20.000000      1      0    7.9250     0         1
219       1    0  45.000000      0      0   26.5500     1         1
220       1    1  17.000000      1      0  108.9000     1         3
221       3    0  43.000000      0      0    6.4500     0         1
222       2    0  36.500000      0      2   26.0000     1         1

[223 rows x 8 columns]

In [32]:
test_data=test_data.values
test_data=np.append(test_data,title_in_test.reshape(-1,1),axis=1)
test_data.shape

(223, 9)

# Applying Logistic Regression algorithm for the given data

In [33]:
clf = LogisticRegression(solver='saga',max_iter=10000000, tol=0.00001)
clf.fit(x_train,y_train)

LogisticRegression(max_iter=10000000, solver='saga', tol=1e-05)

In [34]:
y_pred = clf.predict(test_data)

In [35]:
np.savetxt('logistic_regression_asgnmt.csv',y_pred,delimiter=",")

In [36]:
y_pred

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 0])

In [37]:
clf.score(x_train,y_train)

0.8053892215568862